@startuml
class Line {
    x1 : int
    x2 : int
    y1 : int
    y2 : int
    + Line()
    + Line(x1:int, x2:int, y1:int, y2:int)
    + setSvg() : void
    + getSvg() : string
    + <<override>> draw() : string
    + statedDrawn() : void
}
Shape <|-- Line
Line o-> "svg" String
@enduml
