@startuml
class Polyline {
    + Polyline()
    + Polyline(poly:String)
    + setSvg() : void
    + getSvg() : string
    + <<override>> draw() : string
    + statedDrawn() : void
}
Shape <|-- Polyline
Polyline o-> "svg" String
Polyline --> "poly" String
@enduml
