@startuml
class Polygon {
    + Polygon()
    + Polygon(poly:String)
    + setSvg() : void
    + getSvg() : string
    + <<override>> draw() : string
    + statedDrawn() : void
}
Shape <|-- Polygon
Polygon o-> "svg" String
Polygon --> "poly" String
@enduml
